### ISSUE TITLE
Quantization to Int8

### ISSUE THREAD

**Issue by alior101** [dscripka/openWakeWord#105]
Hi,
Im trying to work on an internal edge device wake up (esp32s3) in order to enable many users requested capabilities in esphome  - for that, I need the tflite to be quantized to In8. 
tf support for after training quant us limited to importing from keras or tf pb format. Pytorch (the framework used for wakeup trainaing)  can export to onnx but trying tf to load onnx (for export as pb/saved_model)returns unsupported ops (  KeyError: 'onnx::Flatten_0'). 
Any idea how to progress ?

**Comment by dscripka** [comment]
That conversion error is typically just an opset issue with ONNX, but there might be a bigger issue with your goal of quantizing for edge devices like the ESP32-S3.

The underlying speech embedding model that openWakeWord uses is actually relatively large, and I've seen some evidence showing that even when quantized it's far too slow on edge devices to be practical (e.g., it can take several seconds to process on a single 80 ms frame).

Instead, there is [another project here](https://github.com/kahrendt/esphome-on-device-wake-word) that is based on a smaller model and looks very promising. If your goal is wakeword detection on edge devices, this might be the best approach.

**Comment by alior101** [comment]
Thanks!
