### ISSUE TITLE
Duration of negative and positive samples for train

### ISSUE THREAD

**Issue by thatsri9ht** [dscripka/openWakeWord#109]
Hello, I need to train the model that the time value of the negative samples should be 3 seconds? Or can it reach even more than one hour? What should be the best length of time for negative and positive samples? Are the audio clips that Alexa is trained to convert into 3-second clips? Should audio clips be converted into three-second clips? Thank you for your guidance

**Comment by dscripka** [comment]
When training a model, the duration of the positive and negative clips must be the same, as the underlying embedding model operates on a fixed size window and can not process audio of different lengths.

The way that training works allows for any duration of positive and negative clips, but in practice around 2-3 seconds is generally recommended. The Alexa model, for example operates on 2 second clips.

As for the total duration of negative samples, to train a model with reasonable performance you need a large amount, at least 1000 hours in practice.

**Comment by thatsri9ht** [comment]
Thank you for your efforts and the excellent model you have created. I have a few more questions: Is the Alexa model created with two-second clips? Is it possible to use 3-second clips for fine-tuning? Have you utilized any specific method to convert long audio clips into two-second and three-second clips?

Lastly, why does your model, which is very accurate, exhibit a longer response delay compared to the precise wake word model?

**Comment by dscripka** [comment]
Yes, the Alexa model was trained on two-second clips. You can use any duration of clips for training a new model, but past 4-5 seconds the models may begin to become a bit slow.

You can find more details for the audio preparation process in [this notebook](https://github.com/dscripka/openWakeWord/blob/main/notebooks/training_models.ipynb), and also in the `data.py` file in the library.

I'm not sure what you mean by response delay compared to Picovoice Precise; in practice openWakeWord should activate within ~200-300 ms from the end of the spoken wakeword. Are you seeing longer times than this on average?

**Comment by thatsri9ht** [comment]
Yes, almost one second response.
more questions, I have a continuous 50 hour clip, should I split this audio clip into 2 or 3 seconds? Does your model have the ability to divide longer audio clips into clips of a few seconds? Is it possible to fine-tuning the pre-trained Alexa model with 3-second audio clips considering that Alexa is trained for 2 seconds?
Thanks :X

**Comment by dscripka** [comment]
One second is quite long, it should generally be much quicker than that. Can you share more details about your system, and how you are capturing activations?

If you want to train a model on a 50 hour clip, you have to prepare the data as shown in the example [training notebook](https://github.com/dscripka/openWakeWord/blob/main/notebooks/training_models.ipynb), simply splitting it into 2 or 3 seconds is only part of the process. And yes, the data preparation code can help prepare data from clips of arbitrary lengths.

As for finetuning, the models are trained on fixed length clips so it is not possible to finetune them on different durations. If you need an Alexa model that operates on 3 second windows, you would need to train one from scratch.

**Comment by thatsri9ht** [comment]
thanks :X
