### ISSUE TITLE
train_custom_verifier - always a ValueError

### ISSUE THREAD

**Issue by ser** [dscripka/openWakeWord#112]
I am trying to train custom verifier and whatever I do, I get `ValueError: The positive features were created! Make sure that the positive reference clips contain the appropriate audio for the desired model`

The output is not informative unfortunately. Do the recorded clips must have the same time length? If yes, it's not stated in the docs. How can I identify what's wrong?

```
$ file emoi-ser_01.wav 
emoi-ser_01.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, mono 16000 Hz
```

```
>>> import openwakeword
>>> openwakeword.train_custom_verifier(positive_reference_clips=["emoi-ser_01.wav", "emoi-ser_02.wav", "emoi-ser_03.wav", "emoi-ser_04.wav", "emoi-ser_05.wav", "emoi-ser_06.wav"], negative_reference_clips = ["neg_emoi-ser_01.wav", "neg_emoi-ser_03.wav", "neg_emoi-ser_03.wav", "neg_emoi-ser_04.wav", "neg_emoi-ser_05.wav", "neg_emoi-ser_06.wav"], output_path="/home/whiz/wyoming-openwakeword/wyoming_openwakeword/models/abcd", model_name="/home/whiz/wyoming-openwakeword/wyoming_openwakeword/models/em__oi_v0.1.tflite")
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Processing positive reference clips: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00,  7.32it/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/whiz/.cache/pypoetry/virtualenvs/whiz-sWjmDNrT-py3.11/lib/python3.11/site-packages/openwakeword/custom_verifier_model.py", line 155, in train_custom_verifier
    raise ValueError("The positive features were created! Make sure that"
ValueError: The positive features were created! Make sure that the positive reference clips contain the appropriate audio for the desired model

```

**Comment by dscripka** [comment]
Thanks for pointing out the typo, I fixed the error message in a new commit. It should say the `The positive features were not created!`. This means that in the example audio that you provided, an activation of the wakeword was not found.

The clips to not all need to be the same length, but in general they should be between 3-5 seconds with the wakeword somewhere in the middle. That way the `train_custom_verifier` method can find the wakeword and extract the right features for training.

If you are getting this error, I would double check that these clips work properly with your model when using the `model.predict_clip` method. If not, that means that something is wrong with the clips and/or model.

**Comment by ser** [comment]
Thank you for the fix and explanation. I will close this issue then and work on preparing better clips. 

I will report back here if I have any progress. Thanks again!
