### ISSUE TITLE
Add “beep” sound feature for `capture_activations.py`

### ISSUE THREAD

**Issue by secretsauceai** [dscripka/openWakeWord#12]
# Description
It would be helpful to make a beep sound every time an activation was detected by “capture_activations.py”. This way a user can keep track of wakeups as they occur without checking a screen or logs after the fact.

# DoD (Definition of Done)
- [ ] A user hears a beep upon activation
- [ ] This feature has been tested
- [ ] Documentation of the new feature

**Comment by AmateurAcademic** [comment]
I will work on this; however, I am a bit blocked currently with this #13 installation bug. Once this has been resolved, I will add the feature and submit a PR.

**Comment by dscripka** [comment]
This PR has been merged, and the documentation for the example scripts updated.
