### ISSUE TITLE
Not getting accuracy for custom dataset in testing.

### ISSUE THREAD

**Issue by sanjuktasr** [dscripka/openWakeWord#120]
@dscripka 
1. positive feature dataset ~1 hour -> generated from custom dataset
2. negative feature dataset -> validation_set_features.py
3. used [tra](https://github.com/dscripka/openWakeWord/blob/main/notebooks/training_models.ipynb) to get data features for the positive dataset
4. used 
- openwakeword/openwakeword/train.py --training_config my_model.yaml --generate_clips
-  openwakeword/openwakeword/train.py --training_config my_model.yaml --augment_clips
-  openwakeword/openwakeword/train.py --training_config my_model.yaml --train_model

I am getting >300 False-accept rate per hour.
Please help.

**Comment by dscripka** [comment]
It looks like there is a discussion topic (#121)  very similar to issue; we can continue our discussion there.

In general, the automatic model training process works well _most_ of the time, but not always. Determining the cause of low performance can take some effort.
