### ISSUE TITLE
bug in colab extra feature

### ISSUE THREAD

**Issue by thatsri9ht** [dscripka/openWakeWord#123]
!pip install openwakeword
---successfully--
# Imports
import os
import collections
import numpy as np
from numpy.lib.format import open_memmap
from pathlib import Path
from tqdm import tqdm
import openwakeword
import openwakeword.data
import openwakeword.utils
import openwakeword.metrics

import scipy
import datasets
import matplotlib.pyplot as plt
import torch
from torch import nn
import IPython.display as ipd
----successfully----
F = openwakeword.utils.AudioFeatures()
---------------------------------------------------------------------------
NoSuchFile                                Traceback (most recent call last)
[<ipython-input-8-14dffd871883>](https://localhost:8080/#) in <cell line: 1>()
----> F = openwakeword.utils.AudioFeatures()

2 frames
[/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py](https://localhost:8080/#) in _create_inference_session(self, providers, provider_options, disabled_optimizers)
    470 
    471         if self._model_path:
--> 472             sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
    473         else:
    474             sess = C.InferenceSession(session_options, self._model_bytes, False, self._read_config_from_model)

NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from /usr/local/lib/python3.10/dist-packages/openwakeword/resources/models/melspectrogram.onnx failed:Load model /usr/local/lib/python3.10/dist-packages/openwakeword/resources/models/melspectrogram.onnx failed. File doesn't exist

Hello, I have the above problem in the club, which was not a problem before, apparently the models are not defined in the new version

**Comment by dscripka** [comment]
Newer versions of openWakeWord don't include the models by default in the Python package as this was greatly increasing the file size and limited future model additions.

Now, you can download all of the required models with this command: `openwakeword.utils.download_models()`

Alternatively, you can download individual models manually from this release: https://github.com/dscripka/openWakeWord/releases/tag/v0.5.1
