### ISSUE TITLE
Getting error while training

### ISSUE THREAD

**Issue by sanjuktasr** [dscripka/openWakeWord#125]
![Screenshot from 2024-02-19 16-30-50](https://github.com/dscripka/openWakeWord/assets/124784140/93cbd91f-c2c1-453a-9293-08655f92c3b5)
I tried to augment recorded without generating clips. There is some data dimension issue in training stage. Please help.

**Comment by twitchyliquid64** [comment]
Just started to get this also in the colab notebooks :(

![image](https://github.com/dscripka/openWakeWord/assets/6328589/f7863d6e-e632-4016-a4b9-1252ad47aba6)

**Comment by dscripka** [comment]
Thanks for pointing this out, I found a bug in `train.py` a pushed a [commit](https://github.com/dscripka/openWakeWord/commit/c40fe924ffa12e9ddf24a3e5fcdeb4fd58ab07eb) that should fix this issue.

Let me know if you are still facing this issue after pulling the latest from `main`.

**Comment by twitchyliquid64** [comment]
Running now :)
