### ISSUE TITLE
make a combined model 

### ISSUE THREAD

**Issue by kismeter** [dscripka/openWakeWord#126]
How to make a combined model with all of the steps integrated?

**Comment by dscripka** [comment]
I'm not quite sure what you mean; are you referring to combining multiple different wakeword models?

**Comment by kismeter** [comment]
I mean audio preprocess model and detection model, now they are separated two models, is it possible combine together

**Comment by dscripka** [comment]
Ah, I see. Yes, it would be possible to combine them, but if would produce only very small improvements in efficiency.

This [example notebook](https://github.com/dscripka/openWakeWord/blob/main/notebooks/converting_google_speech_embedding_model.ipynb) shows how the pre-processing model is built in Keras. It would be straightforward to add a classification head to this model, if desired.
