### ISSUE TITLE
My model does not recognize the keyword when I have background noises or speechs

### ISSUE THREAD

**Issue by dilerbatu** [dscripka/openWakeWord#127]
Hey Everyone,

I have trained tons of OWW models and I can say that they work fine in my opinion but when I have some background noise eg. speech. it does not detect at all. How can I prevent that issue ? 

My keyword is Hey Miza and I have used 20000 positive data with 5000 false positive weights and my stepsize is 500000.  Should I change my layer size ? Should I train my model more ? I have used automatic model training. 

Thanks,

Batu.

**Comment by twitchyliquid64** [comment]
I'm no expert, but it might be worth trying `enable_speex_noise_suppression=True`

https://github.com/dscripka/openWakeWord?tab=readme-ov-file#noise-suppression-and-voice-activity-detection-vad

**Comment by dscripka** [comment]
In general, detecting a wakeword in the presence of other speech is the most difficult situation for any wakeword model. While the openWakeWord models can do this reasonably well in some cases, as the the actual wakeword becomes less clear (that is, lower signal-to-noise ratio) compared to the other speech the likelihood that the model will correctly detect the wakeword becomes much lower.

The scenario you describe is a perhaps the most difficult situation for any wakeword model; multiple speakers, far-field audio, and < 0 db signal-to-noise ratio. It's not surprising that the model does not work correctly in this scenario.

Improving performance for this scenario is very challenging, and generally involves more complex combinations of hardware and software. It's unlikely that just adjusting the parameters of the training will make a significant difference here, unless you can collect or simulate training examples very similar to this scenario.
