### ISSUE TITLE
FR: Add ability to specify multiple target words + negative words to automatic training colab

### ISSUE THREAD

**Issue by twitchyliquid64** [dscripka/openWakeWord#129]
Heya!

I'm working on training a bunch of keywords, and it would be useful if I could add multiple pronunciations (i.e I'm australian but my gf is american) as well as negative examples (training 'turn on' vs 'turn off').

**Comment by dscripka** [comment]
The config file used in `train.py` does support some features that might be similar to what you are describing. The [more complete example training notebook](https://colab.research.google.com/drive/1yyFH-fpguX2BTAW8wSQxTrJnJTM-0QAd?usp=sharing) shows how you can adjust the config parameters for greater control over the training process.

Specifically:

[target_phrase](https://github.com/dscripka/openWakeWord/blob/c40fe924ffa12e9ddf24a3e5fcdeb4fd58ab07eb/examples/custom_model.yml#L8) allows you specify multiple wakewords (including those with different pronunciation) when training a model.

[custom_negative_phrases](https://github.com/dscripka/openWakeWord/blob/c40fe924ffa12e9ddf24a3e5fcdeb4fd58ab07eb/examples/custom_model.yml#L13) allows you to specify specific words/phrases that will be added to the negative training data so (hopefully) the model will be less likely to activate on them.
