### ISSUE TITLE
Does adding words in front of wake word improve quality of model ?

### ISSUE THREAD

**Issue by dilerbatu** [dscripka/openWakeWord#131]
Hey Everyone,

I have try to train robust model. In order to make it more accurate, should I add some random generated words in front of the wake word? 

For Example, If we assume that my keyword is Hey Computer,

`config["target_phrase"] = [some_foo_word hey computer, some_foo_word_2 hey computer, ....  some_foo_word_100 hey computer]`

If I generate some foo word around like 100 what will happen ? Any ideas ?

Thanks.

**Comment by dscripka** [comment]
When you say more accurate or more robust, what do you mean? If in your application you expect there to be random speech immediately preceding the target wake word, then yes, adding training data like this could help the model more reliably activate in this situations.

But in general, I wouldn't expect this to improve the performance of the model overall, just in this one area.

**Comment by dilerbatu** [comment]
Thank you for your kind answer !
