### ISSUE TITLE
Would capturing false detections be helpful for fine tuning a model?

### ISSUE THREAD

**Issue by SpenRue** [dscripka/openWakeWord#133]
I have the Jarvis model running on my work station on a MacBook microphone with no noise reduction implemented or anything, but it will have a false wake detection every 10 minutes or so. I have it hooked up to a custom GPT based command processor and have it hooked up so if I say something like "never mind" it will understand not to run any of the other commands it can do.

I was just wondering if I had it store the 3 seconds of audio that caused it to activate when I tell it never mind, if this particular negative data would be worth collecting and fine tuning? Let's say I collected an hour worth of clips that I know where false positives, would you expect it to be at all practical or worth while to fine tune on?

Since there isn't an ability to finetune the onnx models I suppose I would be adding the negative examples to the training data and train from scratch.
https://github.com/dscripka/openWakeWord/issues/79

Just curious what your thoughts are from anyone who as experience with training.

**Comment by dscripka** [comment]
@SpenRue, yes, if you have a relatively large collection of false-activation audio from the target deployment environment, then adding them to the training data for a new model would help significantly.

Though getting false detections every 10 minutes is quite high, so this may be a very challenging environment generally. As a simpler approach that doesn't require re-training the model from scratch, you could trying using the [verifier models](https://github.com/dscripka/openWakeWord/blob/main/docs/custom_verifier_models.md).
