### ISSUE TITLE
audio and piper

### ISSUE THREAD

**Issue by thatsri9ht** [dscripka/openWakeWord#139]
Hello everyone,

I'm encountering longer audio files, some exceeding 3 seconds, particularly in the FMA audio samples model. Could someone please guide me on how to effectively manage these longer samples, perhaps by converting them to 3-second or 2-second durations within the code?
In the provided code from the GitHub repository https://github.com/dscripka/openWakeWord/blob/main/notebooks/automatic_model_training.ipynb, I noticed that the FMA dataset contains audio samples longer than 3 seconds, such as 24 seconds or 29 seconds, etc. How convert these longer audio samples from the FMA dataset into shorter durations, such as 3 seconds or 2 seconds, for use in OpenWakeWord? openwakeword have  a secation for cut audio to 3 seconds or 2 seconds?

Additionally, I'm curious about how the automatic learning feature in the notebook operates on Windows systems. I'm facing an issue with piper-phonemize not being installed. Any insights or tips on this would be greatly appreciated!

Thank you in advance for your assistance.

**Comment by dscripka** [comment]
The data preparation code in the example training notebooks includes functions that handle audio files with varying lengths; you do not need to manually truncate them to a specific duration, unless you are building a custom training pipeline. I would recommend reviewing the functions used in these notebooks, to get a better understanding of the data preparation process, and then you can make any changes necessary for your particular use case.

And that is a good question for Windows systems; in theory it should be possible, but you may need to manually install the `piper-phonemize` library. I have not tested the example notebook on Windows, so there may be other issues as well.

**Comment by thatsri9ht** [comment]
I meant in the (https://github.com/dscripka/openWakeWord/blob/main/notebooks/training_models.ipynb) part for audio converting.
I've a lot of audio files with a duration of more than 3 seconds and almost an hour and two hours, so I need to convert these audio files to less than three seconds. that's right?

**Comment by dscripka** [comment]
If the audio files are an hour or two hours long, then I assume that they contain background audio that would serve as negative data for a custom model? If so, then no, you do not need to truncate them. The data preparation functions will randomly select portions of these clips to mix with the positive samples. If you like, you can manually truncate them to ~10 second clips, which might increase the data preparation efficiency, but it is not required.

And I recommend following [this notebook](https://github.com/dscripka/openWakeWord/blob/main/notebooks/automatic_model_training.ipynb) when training new model. The older notebook you linked above is still valid, but uses slightly different methods and is intended to be instructional, and this won't typically produce the best performing models.
