### ISSUE TITLE
How do we "actually" train new models?

### ISSUE THREAD

**Issue by ryanlath** [dscripka/openWakeWord#15]
I read the theory, but are there any scripts or programs that will do this synthetic data generation for us?  Is that something that will be provided in a future release?

Thanks,
Ryan

**Comment by dscripka** [comment]
@ryanlath Thanks for the request, this is indeed something I am preparing to provide in an upcoming release, including a detailed example showing the data preparation and training process.

In the meantime, I've released the synthetic data generation code in a separate repository here: https://github.com/dscripka/synthetic_speech_dataset_generation

Feel free to experiment with that code, and if you run into any problems create an issue on that repo and I'll try to help resolve it.

**Comment by dscripka** [comment]
@ryanlath, first version of an example notebook for training new models is now in the repo: https://github.com/dscripka/openWakeWord/blob/main/notebooks/training_models.ipynb

Going to close this issue, but if you have other questions or feedback about the tutorial and training custom models, feel free to add them to this discussion thread: https://github.com/dscripka/openWakeWord/discussions/11
