### ISSUE TITLE
CPU consumption is 5x time higher than with precise-lite

### ISSUE THREAD

**Issue by goldyfruit** [dscripka/openWakeWord#153]
Hi @dscripka 

I'm running some tests with OpenWakeWord to see how it performs with Open Voice OS _(and the `alexa` wake word model)_.

One cool thing is that OpenWakeWord seems slightly faster than Precise-Lite but one big caveat _(IMO)_ so far is the CPU consumption which is 5 times higher than with Precise-Lite wakeword engine.

OpenWakeWord running _(23.9% CPU usage)_
```
  26173 goldyfr+   5 -15 1501072 230756  79124 R  23.9  12.2   1:55.95 /home/goldyfruit/.venvs/ovos/bin/python3.11 /home/goldyfruit/.venvs/ovos/bin/ovos-dinkum-listener                                                                      
```

Precise-Lite running _(4.3% CPU usage)_
```
  26339 goldyfr+ -51 -15 1486220 183396  75264 S   4.3   9.7   0:06.39 /home/goldyfruit/.venvs/ovos/bin/python3.11 /home/goldyfruit/.venvs/ovos/bin/ovos-dinkum-listener                                                                      
```

Any idea how to improve this, as for now, on boards such as RPi 3, 4, 5 the trade-off reactivity vs performance doesn't make much sense _(again IMO)_.

Thanks for your great work :+1:

**Comment by dscripka** [comment]
Thanks @goldyfruit, I'm glad you find openWakeWord useful!

I never compared directly to precise-lite in the past, but it is not surprising the it is significantly more efficient than openWakeWord given how efficient many of the Picovoice products are. I am exploring some options that might make the slowest part of openWakeWord (the audio embedding model) faster, but it is unlikely to achieve a 4-5x speedup.

There are other wakeword frameworks that can be used that are more efficient (in particular, I recommend [microWakeWord](https://github.com/kahrendt/microWakeWord)), though it may not (yet) be as easy to train custom wakeword models.

**Comment by goldyfruit** [comment]
Thanks.
