### ISSUE TITLE
Working with Coral Edge TPU in Home Assistant?

### ISSUE THREAD

**Issue by VenominousX** [dscripka/openWakeWord#164]
Hi,

does openwakeword recognize and use a Coral Edge TPU connected via USB in Home Assistant on a Raspberry Pi 5?

With best regards

**Comment by dscripka** [comment]
Unfortunately, the Coral Edge TPU doesn't support all of the operations that the openWakeWord models require, so there isn't a way to leverage it. For a Rasbperry Pi 5, currently only the CPU will be used when running openWakeWord models.

**Comment by VenominousX** [comment]
Thank you @dscripka for the response
