### ISSUE TITLE
Automatic training fails with large negative data

### ISSUE THREAD

**Issue by zionv** [dscripka/openWakeWord#167]
I have generated a large negative data .npy file based on the notebook, when i use this npy file for negative data and try to run the training for the wake word, i got an error that the memory allocation was not possible for a 1.65 TB array. 

So i modified the train.py to load all the npy files with mmap_mode that helped with the np.load, but after the load the code tries to reshape with the np.array this tries to load the entire array into memory and i face the same memory issue. i have searched the internet and i am not able to find a working solution for this. Could someone help me fix this so that i can train a model with large negative and positive data. 

Thanks in Advance.

**Comment by dscripka** [comment]
That is quite a large amount of data! The `train.py` script is designed to use memory mapping to avoid memory issues like this, so while I haven't tried it with a file this large, it should work in theory. What parts of `train.py` did you need to modify? Right now, only the validation a test `.npy` files are loaded fully into memory, and those should be small enough where this isn't an issue.

**Comment by zionv** [comment]
don't know what happend to the reply i sent via email :( so positing it again here:

Thanks for following up on this, the line that is causing the issue is 

"X_val_fp = np.array([X_val_fp[i:i+input_shape[0]] for i in range(0, X_val_fp.shape[0]-input_shape[0], 1)])  # reshape to match model" looks like this tries to load the complete array into memory.

line 868.

what i have also done for all the np.load is as follows:
X_val_fp = np.load(config["false_positive_validation_data_path"],mmap_mode='r+') so that all the arrays are loaded as a memmap and not fully loaded into memory.

Thanks

**Comment by dscripka** [comment]
Thanks for posting the solution. Keeping everything memory mapped is a good approach when memory is limited.
