### ISSUE TITLE
Using other available language models with the automatic_model_training notebook

### ISSUE THREAD

**Issue by tolnai** [dscripka/openWakeWord#181]
It is said that the custom wakeword generation only works for English with the automatic notebook, but there are other language models also available in the release. I'm wondering, why can't those be used?

I changed the notebook to fetch another model (German), and then specify that model when calling generate_samples. The result is some completely different and strange utterance. When checking the code, the generate_samples should look at the model related json config, and then load phonemes with espeak with the proper language, but it looks like the phonemes are recognized wrong.

Am I missing something fundemantal, not being an expert in this field? :)

**Comment by holzmichlnator** [comment]
Same here, i tried the same. I can get the training process to somehow work by changing the hardcoded model in generate_samples.py, but the generated audio files still sound really strange.

**Comment by MaxTheTurtle0** [comment]
Same here. Have you found a way to fix this?

**Comment by dscripka** [comment]
While the underlying Piper TTS system does support other languages, the training code is designed and tested to only work with English at the moment. While it may be possible to load TTS models for other languages, other aspects of the training (e.g., producing negative adversarial examples) right now assumes English text only.

In theory, it is possible to develop a similar training process for non-English languages, but multiple parts of the training process would need to be modified.

**Comment by tolnai** [comment]
Thanks for coming back! Well, I'd love to contribute as a native Hungarian, but unfortunately there is no Hungarian .pt file available in the piper-sample-generator repo, and I'm not sure if any exists at all. However, I could contribute to testing the German variant. Would you have any idea on where to start looking at other languages, or shall I just open a new discussion about supporting the German language?

**Comment by MaxTheTurtle0** [comment]
Hi, I'd be happy to assist with the German version as well if any help is needed.

**Comment by dscripka** [comment]
> Thanks for coming back! Well, I'd love to contribute as a native Hungarian, but unfortunately there is no Hungarian .pt file available in the piper-sample-generator repo, and I'm not sure if any exists at all. However, I could contribute to testing the German variant. Would you have any idea on where to start looking at other languages, or shall I just open a new discussion about supporting the German language?

A new Discussion thread for supporting German would be great. There are two main capabilities needed to support a new language: a multi-speaker TTS model and a phonetic rhyming dictionary. We can discuss potential options for both in that thread.

**Comment by tolnai** [comment]
Alright, moving the discussion here: https://github.com/dscripka/openWakeWord/discussions/196
