### ISSUE TITLE
Missing Models and Resources When Installing openwakeword Library on Windows

### ISSUE THREAD

**Issue by Darthph0enix7** [dscripka/openWakeWord#200]
When installing the openwakeword library on Windows, the resources and models folders, along with their contents, are missing. This causes the C.InferenceSession() class to fail as it searches for melspectrogram.onnx (e.g. anaconda3\envs\torch\Lib\site-packages\openwakeword\resources\models\melspectrogram.onnx), which is not found and i couldnt find a way to bypass it.

I have tried reinstalling the libraries and runtimes multiple times with various changes, but the issue persists. As a workaround, I copied the ONNX models required by the library from an environment installed on my Linux machine, and everything worked correctly. The models are missing when installing on Windows.

```
Traceback (most recent call last):
  File "c:\Users\kalin\Desktop\wakeword_detection\main.py", line 42, in <module>
    owwModel = Model(wakeword_models=[args.model_path], inference_framework=args.inference_framework)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kalin\anaconda3\envs\torch\Lib\site-packages\openwakeword\utils.py", line 686, in wrapped
    return func(*args, **new_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kalin\anaconda3\envs\torch\Lib\site-packages\openwakeword\model.py", line 213, in __init__
    self.preprocessor = AudioFeatures(inference_framework=inference_framework, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kalin\anaconda3\envs\torch\Lib\site-packages\openwakeword\utils.py", line 84, in __init__
    self.melspec_model = ort.InferenceSession(melspec_model_path, sess_options=sessionOptions,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kalin\anaconda3\envs\torch\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\kalin\anaconda3\envs\torch\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 480, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from C:\Users\kalin\anaconda3\envs\torch\Lib\site-packages\openwakeword\resources\models\melspectrogram.onnx failed:Load model C:\Users\kalin\anaconda3\envs\torch\Lib\site-packages\openwakeword\resources\models\melspectrogram.onnx failed. File doesn't exist

```

Please investigate and resolve this issue to ensure that the necessary models and resources are included when installing the openwakeword library on Windows. Thank you!

**Comment by raisbecka** [comment]
Same issue on Win 10. Seems this folder is missing from GitHub directory too

**Comment by dscripka** [comment]
Are you using the latest version of openWakeWord? And did you run `openwakeword.utils.download_models()` prior to loading the models?

I agree that this isn't ideal, and in future releases it likely is better to automatically download the models during installation.

**Comment by raisbecka** [comment]
I did _not_ run download_models(), and that was indeed the issue! Thank you.

By the way: incredible work on this. I managed to get several custom wake-words running very well via Google Collab, and will integrate into a personal assistant I am working on.

**Comment by Darthph0enix7** [comment]
also download_models() fixed the problem for me also but i couldnt see it in any documentation? its no big deal thx

and yeah i twice raisbecka, the lib works like a charm and very easy to produce good models very fast so thanks for that also

**Comment by Darthph0enix7** [comment]
Thx
