### ISSUE TITLE
Wake Word Option does not show when configuring a voice pipeline

### ISSUE THREAD

**Issue by Sk3letor5** [dscripka/openWakeWord#220]
Hey, I am very new to HA and I got a lot of stuff running already. I now tried adding the VA features but I run into a problem with the openwakeword add-on. I have installed the add-on and configured in Wyoming protocol, I also made it accessible to Assist in the Entity Options and tried some other stuff as well. However I can't seem to get the option to configure the wakeword showing up in the Voice Assistant Configuration. I am on the newest Version of Homeassistant OS using Proxmox and followed a tutorial by NetworkChuck on yt. I mostly work on the GUI, but have Samba access configured at least. Anyone knows why this might happen? I would be very happy to add any additional info you might need to help and thanks in advance. I added screenshots of my configuration on the GUI.
![Screenshot 2024-12-06 110704](https://github.com/user-attachments/assets/858a17b7-c2ed-4912-9062-450c5978a6a3)
![Screenshot 2024-12-06 110814](https://github.com/user-attachments/assets/da186d83-6f4e-4877-88e7-4003423ed234)
![Screenshot 2024-12-06 110847](https://github.com/user-attachments/assets/15f2664b-7e9c-463c-84fa-7b98fe92af84)

**Comment by Sk3letor5** [comment]
You have to click on the three dots in the upper right corner of the Voice Pipeline Configuration screen and activate the Wake-Word-Module.

![grafik](https://github.com/user-attachments/assets/a47c90fb-143a-4934-b09e-1d2ba211bbf4)

**Comment by 14790897** [comment]
thanks, this help me
