### ISSUE TITLE
Question: other languages than English

### ISSUE THREAD

**Issue by jenskastensson** [dscripka/openWakeWord#24]
Hi and thanks for this project!
Do you have a rough idea of when you will start adding support for other languages? 
Mimic3 supports some languages, but it lacks quite a few. Possibly I can contribute with missing datasets, please PM me 
Jens

**Comment by dscripka** [comment]
Multilingual support will definitely be the hardest feature to add, as to your point the availability of high quality multi-speaker TTS datasets for non-English languages is often low. I'm considering a few different approaches to address this problem, but I don't know how effective they will be so it will likely be quite a while before I'm able to include support for other languages in future releases.

If you know of good datasets for different languages, that would definitely help! Also feel free to create a [Discussion](https://github.com/dscripka/openWakeWord/discussions) thread on this topic, and I'll try to post updates on experiments as I'm able to complete them.

**Comment by jenskastensson** [comment]
Thank you!
