### ISSUE TITLE
remove 'providers' option for melspec and embedding InferenceSession

### ISSUE THREAD

**Issue by fquirin** [dscripka/openWakeWord#27]
Ty for this very interesting open-source wake-word project! I've done some experiments for SEPIA open assistant framework and it looks like it could finally become a real alternative to Porcupine 🙂 (with the exception of custom ww creation for now ^^).

Just a small comment. I'm getting warnings because of 'CUDAExecutionProvider' (`'CUDAExecutionProvider' is not in available provider names`).
I think you can simply remove the `providers` option in the [utils class](https://github.com/dscripka/openWakeWord/blob/main/openwakeword/utils.py#L62) because ONNX runtime will set this to the available providers automatically.

Cu,
Florian

**Comment by fquirin** [comment]
Looking forward to it 👍.

I spent some time to try and find out if I could transport the runtime over to ONNX web, but stopped for now when I realized there are actually 3 ONNX models involved ^^. I'll keep this on my to-do list though since my SEPIA clients are mostly running as web-apps (even the headless one).
Do you have any plans to work on that as well? :-)

**Comment by dscripka** [comment]
This issue will be fixed when #31 is merged, so closing.

And yes, there are three separate models, which I admit is a bit unwieldy when porting to other deployment environments. I have considered making a javascript library before, but it would take some time as much of the functionality in the Python library would need to be ported as well.

Feel free to open a Discussion topic for this though, happy to continue the conversation there.
