### ISSUE TITLE
A subset of wake words can also wake up

### ISSUE THREAD

**Issue by wxqwinner** [dscripka/openWakeWord#33]
When I used 'hey siri' ( it was just a test) as a wake word,
'hey','siri','hey siri' can wake up.

model file [hey_siri.zip](https://github.com/dscripka/openWakeWord/files/12078350/hey_siri.zip)

Is there a trick to solve this problem？

**Comment by dscripka** [comment]
That's a great question @wxqwinner, and is definitely something I've noticed as well when training models. While performance will vary depending on the exact wakeword and training process, I've had reasonable success by generating "adversarial" synthetic examples to use during training to help the model not predict a high score in these situations. For example:

- generate examples of "hey" and "siri" by themselves, and include these as negative clips for training
- generate other words and phrases that sound similar to the target wakeword (like "hey clearly" or "cheery") and include these in the negative clips as well

Note that this will make it harder for the model to learn to distinguish the words and can result in a slight decrease in recall of true positive clips in some cases, so as always careful testing with real-world data from target deployment environment is recommended.
