### ISSUE TITLE
Using custom verifiers throws an exception

### ISSUE THREAD

**Issue by aronweiler** [dscripka/openWakeWord#34]
I trained a couple of custom verifiers for the `hey_jarvis_v0.1` model, and when I call `model.predict(...)` and then say, "hey jarvis" I get the following exception:

**`'Model' object has no attribute 'predict_proba'`**

This originates on [line 306 of model.py](https://github.com/dscripka/openWakeWord/blob/ab329a5f34e6ce35c0cecc54ad104b668493690b/openwakeword/model.py#L306)

Is there something I am doing wrong here?

Here is my code for adding the each of the custom verifiers to the model.  
``` python
# Create the model
model = Model(wakeword_models=self.args.wake_word_models) # using hey_jarvis_v0.1 here

# For each custom verifier, add it to the model
for custom_verifier in self.args.custom_verifiers:            
    custom_verifier_model = Model(
        wakeword_models=self.args.wake_word_models,
        custom_verifier_models={"hey_jarvis_v0.1": custom_verifier.model}, # that's the path to the pkl
        custom_verifier_threshold=0.3, # the threshold score required to invoke the verifier model
    )
    model.custom_verifier_models["hey_jarvis_v0.1"] = custom_verifier_model 
```

**Comment by dscripka** [comment]
I think the issue is with this line:

```python
model.custom_verifier_models["hey_jarvis_v0.1"] = custom_verifier_model 
```
You don't need to manually set the custom verifier model after instantiating an openWakeWord `Model` object, as they are [already loaded](https://github.com/dscripka/openWakeWord/blob/ab329a5f34e6ce35c0cecc54ad104b668493690b/openwakeword/model.py#L184) during initialization. So if you want to load multiple different verifier models for the same underlying base model, you'll also need to have multiple `Model` objects.

**Comment by aronweiler** [comment]
Thank you for your response.  I see now that you can only have one custom verifier for each model.

I've modified my code where I load the models to look like this:
``` python
# Can only have one custom verifier per model.  See https://github.com/dscripka/openWakeWord/issues/34            
# Create a model for each custom verifier in our wake word models configuration
verifier_models = []            
for wake_word_model in self.args.wake_word_models:           
    if wake_word_model.training_data is None:
        # No training data is available, create the model without the custom verifier
        model = Model(wakeword_models=[wake_word_model.model_path])
    else:
        # Training data is available, use a custom verifier
        model = Model(wakeword_models=[wake_word_model.model_path],
            custom_verifier_models={wake_word_model.model_name: wake_word_model.training_data},
            custom_verifier_threshold=0.5)
    
    verifier_models.append({"wake_word_model": wake_word_model, "model": model})
```

Then later I add all of the predictions to a list.
``` python
# Predict on each model
predictions = []
for model in verifier_models:
    predictions.append({"prediction": model["model"].predict(mic_audio), "wake_word_model": model["wake_word_model"]})
```

Finally, I end up pulling out the highest scoring prediction:
``` python
prediction = None
for wake_word_model in self.args.wake_word_models:           
    a_prediction = max(predictions, key=lambda item: item["prediction"][wake_word_model.model_name])
    if prediction is None or a_prediction["prediction"][wake_word_model.model_name] > prediction["prediction"][wake_word_model.model_name]:
        prediction = a_prediction
```
And that gives me the highest scoring prediction out of all of the models / wake words.

I'm pretty new to python, so this might be really hacky...  I'd appreciate any feedback!

I also just want to say that your library has been very easy to work with- I am working on a custom voice assistant project with my daughter, and now it has the capability to answer each of us differently based on these custom verifiers.  

Thanks again for your work!

**Comment by dscripka** [comment]
Thank you for the very kind feedback, @aronweiler, and that sounds like an excellent project to work on with your daughter! There are some [other discussions](https://podcastsdataset.byspotify.com/) about adding speaker identification support to openWakeWord, and I had thought about using the verifier models for that purpose but haven't tried it yet. It's interesting to hear that it might have potential!

And your code looks good, thanks for including examples in the issue. I might consider adding a feature to a future release of openWakeWord that allows for multiple verifier models for a single base model, and I'll be sure to use your use-case as a reference.
