### ISSUE TITLE
Nagative Sample Set for Custom Wake Word Generation

### ISSUE THREAD

**Issue by ab-tools** [dscripka/openWakeWord#35]
Hello @dscripka,

first thanks a lot for your efforts with providing an open source wake word solution - this is really great!

I'm currently preparing the data set to train a custom model based on your great [tutorial](https://github.com/dscripka/openWakeWord/blob/main/notebooks/training_models.ipynb) and with the help of your ["synthetic_speech_dataset_generation" repository](https://github.com/dscripka/synthetic_speech_dataset_generation) I was also easily able to generate the ~100,000 positive samples.

But honestly, I'm struggling a bit with the negative ones. In all your [pre-generated openWakeWord models](https://github.com/dscripka/openWakeWord/tree/main/docs/models) it mentions this big data set for negative data:
```
The model was trained on approximately ~31,000 hours of negative data, with the approximate composition shown below:

    ~10,000 hours of noise, music, and speech from the [ACAV100M dataset](https://acav100m.github.io/)
    ~10,000 hours from the [Common Voice 11 dataset](https://commonvoice.mozilla.org/en/datasets), representing multiple languages
    ~10,000 hours of podcasts downloaded from the [Podcastindex database](https://podcastindex.org/)
    ~1,000 hours of music from the [Free Music Archive dataset](https://github.com/mdeff/fma)

In addition to the above, the total negative dataset also includes reverberated versions of the ACAV100M dataset (also using the simulated room impulse responses from the [BIRD Impulse Response Dataset](https://github.com/FrancoisGrondin/BIRD) dataset), and adversarial synthetic generations designed to be phonetically similar to the wakeword (e.g., "annex uh").
```

In the tutorial only a small sample data set is provided. While I could start now downloading similar amount of data from the various sources mentioned above, especially also generating the reverberated versions seems challenging.

As you obviously used the same big negative data set for all the 5 pre-generated wake words, I would assume that you put quite a bit of effort getting the negative samples "right".

And while the positive sample set is obviously very different for each wake word, I would expect the negative one can be very similar if not even the same.

Would you therefore mind just sharing the full big set of ~31,000 hours of negative samples, so other people like me can just download and re-use the same negative sample set you used for generating the existent wake words?

Thanks again for all your efforts
Andreas

**Comment by dscripka** [comment]
Thanks for the great feedback, @ab-tools! I'm glad that you are finding openWakeword and the tutorials useful.

You raise an excellent point about the negative datasets, they are indeed very important to the overall performance of the models. I am considering different ways to potentially share a version of the negative dataset that could be used by others for training new models, but the main challenge is scale: the negative dataset represents nearly a terabyte of raw audio, and I don't currently have a way to efficiently (and cost effectively) host that amount of data. Another option is sharing just the pre-computed openWakeWord features (which are significantly smaller), but that approach greatly limits the amount of customization and augmentation that users can apply to the dataset.

I'm working now on a updated training notebook that significantly streamlines the training process, and perhaps then I can identify a reasonably sized subset of the negative data that is small enough to share but can still yield good performance when used for custom models.

**Comment by dscripka** [comment]
I think sharing a reasonably sized dataset of pre-computed features for negative data makes sense, I'll plan to release that along with the updated training notebook soon. In the future, I agree that sharing the complete data preparation code for larger datasets is the best option.

I'm glad that you were able to fix the issue with the different number of time steps. As for the number of epochs, it often varies depending on the model, but typically it is more than 10. The best way to determine the optimal number of epochs for training is to have a small development set so that you can determine if the model is overfitting.

**Comment by dscripka** [comment]
Yes, that's the type of approach I would recommend. In fact, the closer your development set is to a deployment scenario, the better performance will be. For example, I will often use a dev set of a few hundred positive examples, and then a few hours of negative examples (the [Dipco corpus](https://www.amazon.science/publications/dipco-dinner-party-corpus) is a good option for this). That way you can estimate both recall and the false positive rate per hour, and then determine the best point to stop training.
