### ISSUE TITLE
RuntimeError: The size of tensor a must match the size of tensor b

### ISSUE THREAD

**Issue by madgrizzle** [dscripka/openWakeWord#43]
I'm trying to train a custom wakeword and after it processes the positive clips and starts to create batches, it errors out with the above error message.

> 200it [00:00, 210769.05it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:00<00:00, 24746.62it/s]
1000it [00:00, 211491.73it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:00<00:00, 22787.95it/s]
5000it [00:00, 206236.00it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████| 5000/5000 [00:00<00:00, 23351.82it/s]
6096 negative clips after filtering, representing ~12.0 hours
 98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▋  | 94/96 [04:54<00:06,  3.13s/it]
15it [00:00, 22.05it/s]                                                                                                                              
178it [00:00, 96147.60it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 178/178 [00:00<00:00, 20622.79it/s]
122 positive clips after filtering
Traceback (most recent call last):
  File "/home/john/wakeword/train.py", line 138, in <module>
    mixed_clips, labels, background_clips = next(mixing_generator)
  File "/home/john/wakevenv/lib/python3.10/site-packages/openwakeword/data.py", line 423, in mix_clips_batch
    mixed_clip = mix_clip(fg, bg, snr, start)
  File "/home/john/wakevenv/lib/python3.10/site-packages/openwakeword/data.py", line 489, in mix_clip
    bg[start:start + fg.shape[0]] = bg[start:start + fg.shape[0]] + scale*fg
RuntimeError: The size of tensor a (23107) must match the size of tensor b (29696) at non-singleton dimension 0

I assume this is something wrong with how I have it set-up and not a bug, but is there any suggestions you can provide to help me hunt this issue down?

**Comment by madgrizzle** [comment]
Turns out the error might have been due to relatively few samples.

**Comment by dscripka** [comment]
> Turns out the error might have been due to relatively few samples.

That can happen sometimes with scripts used in the example notebook. An upcoming release with include new training notebooks and code that should resolve this issue. Thanks for the reminder!
