### ISSUE TITLE
Issue with following the notebook

### ISSUE THREAD

**Issue by danives** [dscripka/openWakeWord#47]
Hey,

So I was following along with your notebook, using my own generated dataset of wake word phrases. The first issue I ran into was that I needed to download some additional packages, namely:

```
!pip install mutagen
!pip install acoustics
```

The main issue, however, is when I get to the point of using the mixing generator, I get the following error:

```
0%|          | 0/919 [00:00<?, ?it/s]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-15-d0a317d9a8ea>](https://localhost:8080/#) in <cell line: 10>()
      8 
      9 row_counter = 0
---> 10 for batch in tqdm(mixing_generator, total=N_total//batch_size):
     11     batch, lbls, background = batch[0], batch[1], batch[2]
     12 

2 frames
[/usr/local/lib/python3.10/dist-packages/openwakeword/data.py](https://localhost:8080/#) in mix_clip(fg, bg, snr, start)
    487     snr = 10 ** (snr / 20)
    488     scale = snr * bg_rms / fg_rms
--> 489     bg[start:start + fg.shape[0]] = bg[start:start + fg.shape[0]] + scale*fg
    490     return bg / 2
    491 

RuntimeError: The size of tensor a (10445) must match the size of tensor b (14388) at non-singleton dimension 0
```

I'm not sure if the library has changed since the notebook was made?

**Comment by dscripka** [comment]
Hey @danives , I think another user had a similar error (https://github.com/dscripka/openWakeWord/issues/43), but I'm not sure if source of your issue would be the same. This is likely and edge case that I need to investigate further.

Also, I am just about to release a new training procedure (https://github.com/dscripka/openWakeWord/pull/48) for custom models that will simplify the entire process substantially (as well as fix the dependency errors you pointed out). Hopefully that will apply to your use-case, but let me know if not, and I'll try to determine the cause of this particular error.
