### ISSUE TITLE
How to deploy openwakeword to android use onnxruntime

### ISSUE THREAD

**Issue by huyletran** [dscripka/openWakeWord#49]
How to deploy to android use onnxruntime? Thanks

**Comment by dscripka** [comment]
Hey @huyletran, that's a good question. ONNX is supported on Android (https://onnxruntime.ai/docs/tutorials/mobile/), so it should be possible in theory to run the three core models for openwakeword (the melspectrogram, embedding, and classifier models). However, you would likely need to re-implement the orchestration code to run the models and manage the inputs and outputs. There is some discussion in the [FAQ](https://github.com/dscripka/openWakeWord#faq) on doing this for other frameworks (e.g., C++) so you might be able to find some good inspiration there.

**Comment by huyletran** [comment]
After melspectrogam goes through the embedding model, there is a shape that is a tensor: float32[unk__315,1,1,96]. How to handle features and put them into the model classifier shape tensor: float32[1,28,96]?

**Comment by dscripka** [comment]
The embedding model can take in a melspectrogram of varying sizes (corresponding to different lengths of audio data), so the `unk__315` dimension is determined by the size of your input melspectrogram. You'll need to manually feed the embedding model output embedding tensor chunk by chunk in the shape of [28, 1, 1, 96] tensors if your classifier model expects an input of [1,28,96]. Then just add or remove unit dimensions as needed to get the tensor chunk into the right shape for the classifier model.

**Comment by huyletran** [comment]
So it is necessary to divide the melspectrogram into small parts of size [28, 1, 1, 96] with window size of 76? Can you tell me about preprocess after give into 3 model
