### ISSUE TITLE
Run using Coral accelerator

### ISSUE THREAD

**Issue by jhbruhn** [dscripka/openWakeWord#51]
Would it be possible to run this using a Coral Accelerator to offload the work from the CPU, or does the model include operations not supported by the Coral TPUs?

**Comment by dscripka** [comment]
Unfortunately, the core audio embedding model of openWakeWord uses a [Leaky ReLU[](https://paperswithcode.com/method/leaky-relu) activation function which does not appear to be compatible with the Coral Accelerator based on [this page](https://coral.ai/docs/edgetpu/models-intro/#model-requirements).

**Comment by luka6000** [comment]
@dscripka do you think there would be any advantage over using Coral? It seams it should be pretty easy to replace Leaky ReLU with [Parameterized ReLU](https://paperswithcode.com/method/prelu)

**Comment by dscripka** [comment]
It would depend on the type of deployment scenario. Currently the entire openWakeWord stack of models can run easily on a single core of a Raspberry Pi3. This is not as efficient as it could be, but I wouldn't consider this computationally intensive either.

If you have a workload that requires many simultaneous instances of openWakeWord, something like the Coral could be beneficial. However, a more powerful CPU or simple GPU is likely substantially more cost efficient and much easier to implement in practice.
