### ISSUE TITLE
[Feature request] Multiple wake words

### ISSUE THREAD

**Issue by edurenye** [dscripka/openWakeWord#57]
Would be nice to be able to activate the Home Assistant pipline with different words, you want a model that gets activated with those diferent words.
In case of a home with multiple people or kids and they want to use their favorite movie character name or whatever.

**Comment by dscripka** [comment]
This is actually possible now with openWakeWord, if you use the [advanced training notebook](https://colab.research.google.com/drive/1yyFH-fpguX2BTAW8wSQxTrJnJTM-0QAd?usp=sharing), you can provide multiple unique words and phrases and a single model that responds to all of them will be trained. You will likely have to adjust some other training config parameters as well when well doing this, though. Specifically:

```python
config["model_name"] = "my_model_name"
config["n_samples"] = 1000  # increase this as you will need more samples when training on multiple words
config["steps"] = 10000  # increase this as you will need to train for longer when using multiple words
```
