### ISSUE TITLE
Making custom wake word

### ISSUE THREAD

**Issue by kevvar** [dscripka/openWakeWord#63]
Hi guys, working on google collab to create a custom wake word for Home Assistant I’m facing an issue using the notebook:

![image](https://github.com/dscripka/openWakeWord/assets/70792969/f5030442-7915-4685-b096-9dec7cb907d2)

Is this a criticial issue? Does it mean I wouldn’t have a good model to work?
It doesn´t stop working just says that

**Comment by dscripka** [comment]
This is not a critical issue, and the model training process is unaffected. As long as the notebook continues and the training process completes without other issues, the model should perform normally.

Thank you for pointing this out, though. In the future I will update the notebook setup to avoid this issue as I see how it can be confusing.

**Comment by kevvar** [comment]
Thanks a lot @dscripka
