### ISSUE TITLE
Fintuning for a specific person voice 

### ISSUE THREAD

**Issue by alior101** [dscripka/openWakeWord#79]
Hi,
Any idea on how to finetune an already existing tflite model (alexa for example) to increase the detection performace for a specific set of people ? The Colabs notebooks are great for a custom wake up word but I couldn't find some easy way to start from a trained model and just finetuning using a small set of positives

**Comment by alior101** [comment]
Some clarifications: I'm not talking about custom verfication model that filters false positives for a specific set of persons. The issues I'm having with wake up word detection is that it's not detected frequenctly enough (playing with threshold didnt help) - probabaly due to me being a non native english and having an accent which I'd like to finetune for...

**Comment by dscripka** [comment]
@alior101 if the custom verification models don't seem to be working well for this purpose, then unfortunately there currently isn't a way to finetune an existing tflite or onnx to respond better to a specific speaker.

Better support for non-native english speakers and training non-english models is certainly something I'm working on as it's one of the biggest current limitations of openWakeWord. To that point, Coqui recently released their [xTTS-v2 model](https://huggingface.co/coqui/XTTS-v2) which seems promising for this application. I'm planning some experiments in the near future to see if this may enable creating non-english models, but I think this could also improve performance across different accents for english models.

If you are interesting in experimenting as well, evaluating how well xTTS-v2 can create speech similar to yours would be a good first step in determining the potential value of this approach.

**Comment by alior101** [comment]
Sounds interesting I will look into that.
What about taking few recorded wake up words from HomeAssistant itself (in debug mode) and adding those recordings to the synthetically generated trainging set  (maybe adding them multiple time to weight it more), and retrain from scratch ? Does that sound promising ?

**Comment by dscripka** [comment]
Yes, adding recordings of real wake words from target speakers to the training data will very likely improve performance for those speakers. I'm not sure how many would be required for good performance but it is certainly worth a try. In fact, if this approach improves detection even a relatively small amount, this may enable you to use the custom verifier models to further improve performance.
