### ISSUE TITLE
Train the Model - failed due to missing yaml definition

### ISSUE THREAD

**Issue by kds69** [dscripka/openWakeWord#83]
Hi, after downloading the data when running training on google colab, I got below error:

`NameError                                 Traceback (most recent call last)

[<ipython-input-3-ab8a2170a404>](https://localhost:8080/#) in <cell line: 34>()
     32 
     33 # Load default YAML config file for training
---> 34 config = yaml.load(open("openwakeword/examples/custom_model.yml", 'r').read(), yaml.Loader)
     35 
     36 # Modify values in the config and save a new version

NameError: name 'yaml' is not defined`

**Comment by dscripka** [comment]
It's likely that this issue has been fixed by recent updates today to the `train.py` code and the Google Colab notebooks. Please try the latest versions of the Colab notebooks, and let me know if you have any more problems.

**Comment by kds69** [comment]
worked!
thanks a lot!
