### ISSUE TITLE
[Help] How to train a model like timer

### ISSUE THREAD

**Issue by jinlife** [dscripka/openWakeWord#89]
Hello dscripka,

I found that all the training target phrase examples were models of one fixed sentence.
But timers contain different class_mappings in a model like below code.
Could you please share an example of how to train a model like timer? It's very useful for working with variables in sentences.

Thanks.

`model_class_mappings = {
    "timer": {
        "1": "1_minute_timer",
        "2": "5_minute_timer",
        "3": "10_minute_timer",
        "4": "20_minute_timer",
        "5": "30_minute_timer",
        "6": "1_hour_timer"
    }
}`

**Comment by dscripka** [comment]
Yes, the current training code only trains models with binary predictions. As you point out, the original timer models do have multiple potential outputs, but this was more of an experiment to see if this approach was possible. While it does work, I have found that the performance of this type of model is generally lower than that of multiple binary models, so it hasn't been a priority for the past few releases.

Can you describe more of this "variables in sentences" use case? Perhaps there is another way to approach this with multiple models, but if not, I can certainly consider adding multi-class models back on the roadmap for future releases.

**Comment by jinlife** [comment]
Thank you for your reply. I appreciate your explanation. I was thinking of adding 1, 2, 3…100 slots for the same command, but I understand that it may require 100 models. Maybe it would be possible to handle it in one model with different classes, which might be neater. Also I hope to learn more knowledge from you about this.

**Comment by dscripka** [comment]
If your intent is to have a single model respond to multiple phrasings of the same command (e.g., "turn on the lights", "turn the lights on", etc.) this is possible now just by having configuring multiple example phrases for the model. In this way you can have a single model response to many different expressions of the same wake phrase.

You can then even extend this approach, and produce multiple models for several high-level categories of different intents/commands, and so your total set of models will be much less than 100. Of course, there are some limits to this approach (a single model has limits on how many different phrases it can accurately detect), but this method may get you quite far.

**Comment by jinlife** [comment]
Please accept my apologies for not describing clearly. I meant that one command with a variable number would lead to different actions. For example, "Go to Location 1" would move it to slot 1 and "Go to Location 2" would move it to slot 2. etc. If there are many slots, then there would be many models. It would be neat to keep it in one model since command are the same, only slots are variable.

**Comment by dscripka** [comment]
Ah, I understand now. Yes, that type of application might be suited to a single model, though I not sure how well it would perform with that many slots.

I may try to enable this functionality again in the future, but in the meantime I would recommend at least trying the approach with a separate model for each slot. The actual wakeword models are very small, so on a reasonably capable system (e.g., a recent desktop CPU with at least 4 cores) running dozens or even hundreds of models simultaneously is certainly possible.

**Comment by jinlife** [comment]
Got it. I will try the separated models. Thank you.
