### ISSUE TITLE
Training gets stuck at "Resolving data files"

### ISSUE THREAD

**Issue by darkenergymedia** [dscripka/openWakeWord#92]
completely open to the idea that i'm just doing something entirely wrong, but whether i run the simplified Colab training or attempt to walk through the standard "automatic_model_training.ipynb" process, it gets to "Resolving data files" during the download portion, and this will then stay at 0% indefinitely, never moving on from this point. 

i have tried on multiple google accounts and a couple of different browsers, as well as attempting to search for a solution but haven't had much luck. just wondering if it's something simple i'm doing wrong.

the sticking seems to happen here:

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:72: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Downloading readme: 100% 936/936 [00:00<00:00, 43.2kB/s]
Resolving data files: 0% 0/270 [00:00<?, ?it/s]

sorry if this is high noob status stuff.

**Comment by dscripka** [comment]
I was able to re-produce this issue in Colab (strangely, it worked fine locally), there does seem to have been some change either in Colab or with HuggingFace that prevents downloading one of the datasets.

I updated the Colab training notebook to download this data an alternate way, which seems to be working correctly. If you are still having issues, please report any errors here and I'll continue investigating.

**Comment by darkenergymedia** [comment]
running a training now and so far all seems to be working! made it through the download phase and on to the training phase. thanks for sorting that out so quickly!
