### ISSUE TITLE
error "name yaml is not defined" in Yupyter Notebook to train new wakewords

### ISSUE THREAD

**Issue by barrystaes** [dscripka/openWakeWord#94]
I got the error `name 'yaml' is not defined` at the first line of code in step "3. Train the Model" of `automatic_model_training_simple.ipynb`. This playbook is the [wake word training environment](https://colab.research.google.com/drive/1q1oe2zOyZp7UsB3jJiQ1IFn8z5YfjwEb?usp=sharing#scrollTo=1cbqBebHXjFD) linked on https://www.home-assistant.io/voice_control/create_wake_word/ I could not find a copy of this source code in this repo (might be an idea?) but here seems to be the best place to report this..

Fix:  
It seems to be fixed by inserting `import yaml` in the running Jupyter Notebook. (i should say probably fixed; it is still running but did not crash at the start like the other times)

**Comment by barrystaes** [comment]
Can confirm this fixed the notebook. 

And I see the non-simple version https://github.com/dscripka/openWakeWord/blob/main/notebooks/automatic_model_training.ipynb also uses `yaml.load` and does include an `import yaml` in the Environment Setup.

**Comment by sujitvasanth** [comment]
Hi I tested today and initially did get your error,
I think you have to clear all the notebook outputs and wait for 2 to generate.
I also did add import yaml to part 3
It all worked and my trained examples worked really well as wake words..
just an observation that the output model name n model prediction  is dependent on the filename and not hard coded into the neural net

This is definitely the way to go with making it easy to create custom training easily for end users

**Comment by dscripka** [comment]
There is an `import yaml` statement in the code for the 2nd step of the simple training notebook, so you shouldn't get this error unless there was a problem with step #2.

But just in case, I added another import statement for step #3. Thanks for pointing out the potential issue.
