### ISSUE TITLE
use huggingface libraries

### ISSUE THREAD

**Issue by sujitvasanth** [dscripka/openWakeWord#96]
I see you have an example on hugging face https://huggingface.co/spaces/davidscripka/openWakeWord spaces using gradio which was great to demonstrate the accuracy of openwakeword
In the future programmers will often use openwakeword prior to offline speech recognisers such as distil-whisper which use the transformer library.
is there any way of using the huggingface library to run inference for openwakeword or to produce models that can?

**Comment by dscripka** [comment]
I'm glad you like the demo!

As for using huggingface libraries, right now the actual models behind openWakeWord are relatively small and simple, so there wouldn't be a significant benefit to porting them to the huggingface library. It certainly is possible in theory, though, and perhaps I can consider this in future releases.

**Comment by sujitvasanth** [comment]
thanks, hope you do this in the future! This seems to be the best wake word implementation I have seen.
I have written some unpublished add ons for the speechrecognition library to support fasterwhisper and distilwhisper. https://pypi.org/project/SpeechRecognition/ I hope to post these to my github soon.
For hotwords, speechrecognition library it supports snowboy hotword detection (Linux only), I will have a look at adding an openwakeword functionality to it also - which should boost interest in openwakeword.
